server {
    # 1. Nginx слушает 80 порт (обычный HTTP)
    listen 80;

    # 2. Описываем, что делать с запросами, которые пришли на корень сайта ( / )
    location / {
        # 3. Пересылаем запрос на сервис 'python_app' на порт 8000
        # 'python_app' — это имя, которое мы дадим контейнеру в следующем шаге
        proxy_pass http://python_app:8000;

        # 4. Передаем важные заголовки, чтобы Python знал реальный IP клиента
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
