services:
  # 1. Называем наш первый сервис. 
  # Помнишь, мы в nginx.conf указали это имя?
  python_app:
    # Говорим собрать образ из текущей папки (используя наш Dockerfile)
    build: .
    # Говорим Docker, что этот контейнер слушает порт 8000
    # Но мы НЕ открываем его для всего интернета, он виден только для Nginx
    expose:
      - "8000"
    # Если приложение упадет (например, ошибка в коде), Docker сам его поднимет
    restart: always

  # 2. Наш второй сервис — Nginx
  nginx:
    # Берем готовый официальный образ Nginx (версия alpine — самая легкая)
    image: nginx:alpine
    # Соединяем порты: (Порт твоего VPS) : (Порт внутри контейнера)
    # Теперь все, кто зайдет на твой IP, попадут в Nginx
    ports:
      - "80:80"
    # Пробрасываем наш конфиг внутрь контейнера Nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    # Говорим Nginx не запускаться, пока Python-приложение не будет готово
    depends_on:
      - python_app
    restart: always
